
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SASL_ENABLED: "true"
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf
    volumes:
      - ./secrets/zookeeper_jaas.conf:/etc/kafka/secrets/zookeeper_jaas.conf:ro
      - ./data/zookeeper:/var/lib/zookeeper/data
      - ./data/zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # PLAINTEXT external
      - "9093:9093"      # SSL external
      - "9095:9095"      # SASL_SSL external
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Map listener names to protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL,PLAINTEXT_INTERNAL:PLAINTEXT

      # Advertise external listeners for clients outside Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,SSL://localhost:9093,SASL_SSL://localhost:9095,PLAINTEXT_INTERNAL://kafka:19092

      # Bind to all interfaces
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_SSL://0.0.0.0:9095,PLAINTEXT_INTERNAL://0.0.0.0:19092

      # Inter-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      # SSL and SASL settings
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.p12
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka_keystore_creds
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka_truststore_creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka_ssl_key_creds
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf

    volumes:
      - ./secrets:/etc/kafka/secrets:ro
      - ./data/kafka:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"    # HTTP (for dev)
      - "8082:8082"    # HTTPS (secured)
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      # Enable both HTTP and HTTPS listeners
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081,https://0.0.0.0:8082"

      # Kafka connection over internal PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092

      # SSL configuration (reusing Kafka certs)
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.keystore.p12
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: changeit
      SCHEMA_REGISTRY_SSL_KEYSTORE_TYPE: PKCS12
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: changeit 
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.truststore.jks
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: changeit
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE: JKS

    volumes:
      - ./secrets:/etc/kafka/secrets:ro
